<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="State\Authenticators\**" />
    <EmbeddedResource Remove="State\Authenticators\**" />
    <None Remove="State\Authenticators\**" />
    <Page Remove="State\Authenticators\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AristotelisThesis.Domain\AristotelisThesis.Domain.csproj" />
  </ItemGroup>

</Project>
